# Generated by Django 5.2.7 on 2025-10-15 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("astar", "A* Search"),
                            ("bfs", "Breadth-First Search"),
                            ("dfs", "Depth-First Search"),
                            ("dijkstra", "Dijkstra"),
                            ("hill_climbing", "Hill Climbing"),
                            ("simulated_annealing", "Simulated Annealing"),
                            ("genetic", "Genetic Algorithm"),
                        ],
                        max_length=50,
                    ),
                ),
                ("grid_data", models.JSONField()),
                ("start_position", models.JSONField()),
                ("goal_position", models.JSONField()),
                ("heuristic", models.CharField(blank=True, max_length=50)),
                ("path_found", models.BooleanField(default=False)),
                ("path", models.JSONField(blank=True, null=True)),
                ("steps", models.JSONField(blank=True, null=True)),
                ("nodes_explored", models.IntegerField(default=0)),
                ("path_cost", models.FloatField(default=0.0)),
                ("execution_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
