# Generated by Django 5.2.7 on 2025-10-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="board_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulation",
            name="final_state",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulation",
            name="initial_state",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulation",
            name="simulation_type",
            field=models.CharField(
                choices=[
                    ("pathfinding", "Pathfinding"),
                    ("8-puzzle", "8-Puzzle"),
                    ("n-queens", "N-Queens"),
                    ("sudoku", "Sudoku"),
                    ("tic-tac-toe", "Tic-Tac-Toe"),
                    ("tower-of-hanoi", "Tower of Hanoi"),
                    ("connect4", "Connect 4"),
                ],
                default="pathfinding",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="solved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="simulation",
            name="total_moves",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="algorithm",
            field=models.CharField(
                choices=[
                    ("astar", "A* Search"),
                    ("bfs", "Breadth-First Search"),
                    ("dfs", "Depth-First Search"),
                    ("dijkstra", "Dijkstra"),
                    ("hill_climbing", "Hill Climbing"),
                    ("simulated_annealing", "Simulated Annealing"),
                    ("genetic", "Genetic Algorithm"),
                    ("8-puzzle-astar", "8-Puzzle A*"),
                    ("8-puzzle-bfs", "8-Puzzle BFS"),
                    ("n-queens", "N-Queens"),
                    ("sudoku", "Sudoku"),
                    ("tic-tac-toe-minimax", "Tic-Tac-Toe Minimax"),
                    ("tic-tac-toe-alphabeta", "Tic-Tac-Toe Alpha-Beta"),
                    ("tower-of-hanoi", "Tower of Hanoi"),
                    ("connect4", "Connect 4"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="goal_position",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="grid_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="start_position",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
